/* 
const myPromise = new Promise((resolve, reject) => {
  const user = null;

  if (!user) {
    reject('Something went wrong!');
  } else {
    setTimeout(() => {
      resolve('Successfully get the data');
    }, 1000);
  }
});

myPromise
  .then((res) => console.log('From Then:', res))
  .catch((err) => console.log('From Catch:', err));
 */
/* 
const myPromise2 = new Promise((resolve, reject) => {
  const user = null;

  if (!user) {
    reject('Something went wrong!');
  } else {
    setTimeout(() => {
      resolve('Successfully get the data...');
    }, 1000);
  }
});

myPromise2
  .then((res) => console.log('From Then:', res))
  .catch((err) => console.log('From Catch:', err));
 */
